### ISSUE TITLE
输出到25页时出现IndexError: list index out of range

### ISSUE THREAD

**Issue by dph233** [dcsgman/WebCrawler#1]
输出到25页时弹出错误

  File "C:/Users/sds/Desktop/untitled0.py", line 112, in <module>
    score = item.select("div.comment > h3 > span.comment-info > span")[1]

IndexError: list index out of range

修改了获取评论内容的方式之后虽然可输出的页数变多了,但还是有页面连续空白的情况.

**Comment by Flians** [comment]
https://movie.douban.com/subject/26363254/comments?start=200&limit=20&sort=new_score&status=P&percent_type=
第8条评论没有评分，所以在分割的时候[1]数组越界

**Comment by dph233** [comment]
谢谢解答~不过25页这个问题貌似是因为当start的数值大于等于500的时候,页面就会变成"还没有人写过短评",所以接下来的页面都无法获取评论了,不知道是不是豆瓣反爬虫的策略...这个问题不知道该如何解决:(   真的很感谢你的代码!~

**Comment by dph233** [comment]
谢谢解答不过25页这个问题貌似是因为当start的数值大于等于500的时候,页面就会变成"还没有人写过短评",所以接下来的页面都无法获取评论了,不知道是不是豆瓣反爬虫的策略...这个问题不知道该如何解决:( 真的很感谢你的代码!
